"""`.sync.json` sidecar — the reversible alignment record polysync emits.

One sidecar per original input, written next to it as `<input>.sync.json`.
Originals are never modified. Downstream aligns the source to the reference
timeline with `ffmpeg -itsoffset delta_seconds` (optionally
`atempo=1+drift_slope` for long-form lip-sync).
"""
import json
from pathlib import Path

SCHEMA_VERSION = 1


def sidecar_path(media_path):
    """Sidecar lives next to the original, named `<original>.sync.json`."""
    media_path = Path(media_path)
    return media_path.with_suffix(media_path.suffix + ".sync.json")


def write_sidecar(media_path, *, source, reference, delta_seconds, drift_slope,
                  overlap_in_reference, overlap_in_source, verification=None):
    """Write the canonical sidecar next to `media_path` and return its Path."""
    sc = {
        "_about": (
            "Sync metadata for %s (aligned to %s). Generated by polysync. "
            "Originals are not modified; downstream uses "
            "ffmpeg -itsoffset delta_seconds to align." % (source, reference)
        ),
        "_help": {
            "delta_seconds": (
                "Source's t=0 expressed in reference's timeline. "
                "Positive => source starts after reference. "
                "Apply via `ffmpeg -itsoffset <delta_seconds> -i <source>`."
            ),
            "drift_slope": (
                "Residual clock drift between source and reference clocks "
                "(dimensionless, ~1e-5 typical). For camera-cut editing, "
                "ignore. For sync-sound / long-form lip-sync apply "
                "atempo=1+drift_slope to the source."
            ),
            "overlap_in_reference": (
                "[start, end] window in reference's timeline where BOTH source "
                "and reference have valid content. Use to constrain trims/EDLs."
            ),
            "overlap_in_source": (
                "Same window in the source's local timeline "
                "(= overlap_in_reference shifted by -delta_seconds)."
            ),
            "verification": (
                "Filled in by `polysync verify`: median_residual_ms, "
                "residual_spread_ms, probe_count. None until verify runs."
            ),
        },
        "schema_version": SCHEMA_VERSION,
        "source": source,
        "reference": reference,
        "delta_seconds": float(delta_seconds),
        "drift_slope": float(drift_slope),
        "overlap_in_reference": [float(overlap_in_reference[0]),
                                 float(overlap_in_reference[1])],
        "overlap_in_source": [float(overlap_in_source[0]),
                              float(overlap_in_source[1])],
        "verification": verification,
    }
    p = sidecar_path(media_path)
    p.write_text(json.dumps(sc, indent=2, ensure_ascii=False))
    return p


def read_sidecar(input_path):
    """Read `<input>.sync.json`. Returns (delta_seconds, overlap_in_reference,
    has_sidecar). Falls back to (0.0, None, False) if absent or unparseable —
    callers treat that as 'this input is at reference t=0, full coverage'."""
    sc = sidecar_path(input_path)
    if not sc.exists():
        return (0.0, None, False)
    try:
        d = json.loads(sc.read_text())
        if d.get("schema_version") != SCHEMA_VERSION:
            print("WARN: %s schema_version != %d; reading anyway"
                  % (sc.name, SCHEMA_VERSION))
        delta = float(d["delta_seconds"])
        ovl = d.get("overlap_in_reference")
        ovl = (float(ovl[0]), float(ovl[1])) if ovl else None
        return (delta, ovl, True)
    except Exception as e:  # noqa: BLE001 — best-effort, never crash the edit
        print("WARN: failed to parse %s: %s; using delta=0" % (sc.name, e))
        return (0.0, None, False)
